import { Metadata } from "next"

export const metadata = {
  title: {
    default:"Next.js Tutorial",
    template:"%s | Arka"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <div className="bg-yellow-200 h-[20%] w-full">Header</div>
        {children}
      <div className="bg-green-200 h-[20%] w-full">Footer</div>
      </body>
    </html>
  )
}
